name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: The PHP Security Checker
      uses: symfonycorp/security-checker-action@v2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: PHP Lint
      uses: michaelw90/PHP-Lint@2.1.0
      
    - name: Psalm – Security Scanner for PHP
      uses: psalm/psalm-github-security-scan@1.2.1
  
